### PR TITLE
Nikita gostev

### PR DESCRIPTION
**Pull request by Nik121283**
Добавил ПО по определению знака зодиака

### CODE REVIEW

**Review by svetyxley — APPROVED** [review]
Good job!!!!

**Review by nazarzharskyi — APPROVED** [review]
Good👌

**Review by AsakuraAv — APPROVED** [review]
As if everything is good.

**Review by cross-development — APPROVED** [review]
It's better not to use enums like this **EnumZodiacs.Водолей**. But that's a task about git, so...

**Pull request merged**
